name: 'simple cicd solution'

on: push

jobs:
   job1:
     name: first_job
     runs-on: ubuntu-latest
     steps:
       - name: display the path
         shell: bash
         run: echo $PATH
   job2:
     name: second_job
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v4